# Generated by Django 5.2.17 on 2026-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchurnscore',
            name='shap_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
